steps:
# Build the container for md
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/md', '.']
#  dir: 'src'
## Push the container image to Container Registry
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['push', 'gcr.io/$PROJECT_ID/md']
## Deploy container image to Cloud Run
#- name: 'gcr.io/apigee-product-demo/cloud-sdk:1.0.0'
#  entrypoint: gcloud
#  args: ['run', 'deploy', 'md', '--image', 'gcr.io/$PROJECT_ID/md', '--region', '$_REGION','--vpc-connector','vpc-connector','--vpc-egress','private-ranges-only','--update-env-vars','mongohost=10.132.0.2,mongoport=27017,MONGO_USERNAME=appuser,MONGO_PASSWORD=apppwd,BUCKET=$_BUCKET']
#
### And now for the bash part
#
- id: 'Grab apigeecli, fetch details on deployment of cloudrun artifact, and de[;pu based on OAS'
  name: gcr.io/apigee-product-demo/cloud-sdk:1.0.0
  entrypoint: 'bash'
  args:
  - -c
  - |
    cp md.yaml /tmp
    cd /tmp 
    gcloud auth print-access-token > /tmp/token
    #
    ## now let's create the property set file
    #
    echo "target_url=$(gcloud run services describe $_SERVICE --platform managed --region $_REGION --format 'value(status.url)')/md" > /tmp/$_SERVICE.properties
    echo "target_audience=$(gcloud run services describe $_SERVICE --platform managed --region $_REGION --format 'value(status.url)')" >> /tmp/$_SERVICE.properties
    echo "Printing"
    #
    ## Now let's use apigeecli to setup our property set and deploy it all to apigee 
    #
    /tmp/apigeecli prefs set -s=false -o $PROJECT_ID
    echo "/tmp/apigeecli apis create -n $_SERVICE -f $_SERVICE.yaml --oas-google-idtoken-aud-ref=propertyset.$_SERVICE.aud --oas-target-url-ref=propertyset.$_SERVICE.url -t $(cat token) | awk -F '\"' '$2 ~ \"revision\"{print $4}'"
    /tmp/apigeecli apis create -n $_SERVICE -f $_SERVICE.yaml --oas-google-idtoken-aud-ref=propertyset.$_SERVICE.aud --oas-target-url-ref=propertyset.$_SERVICE.url -t $(cat token) | awk -F '"' '$2 ~ "revision"{print $4}' > /tmp/revision
    /tmp/apigeecli resources create  -n $_SERVICE -r /tmp/$_SERVICE.properties -p properties -e $_ENV -t $(cat token)
    /tmp/apigeecli apis deploy -v $(cat revision) -r -n $_SERVICE -t $(cat token) -e $_ENV -s $_GSA@$PROJECT_ID.iam.gserviceaccount.com
    #images:
    #- gcr.io/$PROJECT_ID/md
